[package]
name = "Homepage"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
log = "0.3.8"
simplelog = "^0.4.2"
rand = "0.3"

concurrent-hashmap = "0.2.2"