[development]
address = "localhost"
port = 8001
workers = 2 
log = "normal"
limits = { forms = 32768 }

[staging]
address = "localhost"
port = 8001
workers = 2  
log = "debug"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8001
workers = 2 
log = "normal"
limits = { forms = 32768 }
